trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: '3.11'
  webAppName: 'task-manager-devops-pipeline'
  azureServiceConnection: 'azure-task-manager-connection'

stages:

# =========================
# BUILD STAGE
# =========================
- stage: Build
  displayName: Build and Test

  jobs:
  - job: Build

    steps:

    # Install Python
    - task: UsePythonVersion@0
      displayName: Use Python 3.11
      inputs:
        versionSpec: '$(pythonVersion)'

    # Install dependencies
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: Install dependencies

    # Run tests
    - script: |
        pytest
      displayName: Run tests

    # Create ZIP package
    - task: ArchiveFiles@2
      displayName: Package application
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true

    # Publish ZIP as build artifact
    - task: PublishBuildArtifacts@1
      displayName: Publish application artifact
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
        artifactName: 'drop'
        publishLocation: 'Container'


# =========================
# DEPLOY STAGE
# =========================
- stage: Deploy
  displayName: Deploy to Azure

  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: Deploy

    steps:

    # Download artifact produced by Build stage
    - task: DownloadBuildArtifacts@1
      displayName: Download build artifact
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(Pipeline.Workspace)'

    # Deploy ZIP to Azure App Service
    - task: AzureWebApp@1
      displayName: Deploy Flask application
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        appType: 'webAppLinux'
        appName: '$(webAppName)'
        package: '$(Pipeline.Workspace)/drop/app.zip'
        startUpCommand: 'gunicorn --bind=0.0.0.0:8000 app:app'